// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package players

import (
	json "encoding/json"
	objects "github.com/bombergame/multiplayer-service/game/objects"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAcd0c35fDecodeGithubComBombergameMultiplayerServiceGameObjectsPlayers(in *jlexer.Lexer, out *MessageData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "transform":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Transform).UnmarshalJSON(data))
			}
		case "movement":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Movement).UnmarshalJSON(data))
			}
		case "object_id":
			out.ObjectID = objects.ObjectID(in.Int64())
		case "object_type":
			out.ObjectType = objects.ObjectType(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAcd0c35fEncodeGithubComBombergameMultiplayerServiceGameObjectsPlayers(out *jwriter.Writer, in MessageData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"transform\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Transform).MarshalJSON())
	}
	{
		const prefix string = ",\"movement\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Movement).MarshalJSON())
	}
	{
		const prefix string = ",\"object_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ObjectID))
	}
	{
		const prefix string = ",\"object_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ObjectType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAcd0c35fEncodeGithubComBombergameMultiplayerServiceGameObjectsPlayers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAcd0c35fEncodeGithubComBombergameMultiplayerServiceGameObjectsPlayers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAcd0c35fDecodeGithubComBombergameMultiplayerServiceGameObjectsPlayers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAcd0c35fDecodeGithubComBombergameMultiplayerServiceGameObjectsPlayers(l, v)
}
