// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package players

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (playerMessageData) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*playerMessageData) UnmarshalJSON([]byte) error        { return nil }
func (playerMessageData) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*playerMessageData) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_playerMessageData *playerMessageData
