language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/multiplayer-service .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/multiplayer-service;
          fi

    - stage: deploy
      services:
        - docker
      before_script:
        - echo ${SSH_PASSWORD} && echo "yes" | scp ${SSH_USER}@${SERVER_HOST}:/etc/docker/ca.pem ca.pem
        - echo ${SSH_PASSWORD} && echo "yes" | scp ${SSH_USER}@${SERVER_HOST}:/etc/docker/cert.pem cert.pem
        - echo ${SSH_PASSWORD} && echo "yes" | scp ${SSH_USER}@${SERVER_HOST}:/etc/docker/key.pem key.pem
      script:
        - docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=${SERVER_HOST}:${SERVER_PORT} version
      after_script:
        - rm ca.pem cert.pem key.pem
