language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/multiplayer-service .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/multiplayer-service;
          fi

    - stage: deploy
      services:
        - docker
      before_script:
        - export DOCKER_TLS_VERIFY=1
        - export COMPOSE_TLS_VERSION=TLSv1_2
        - export DOCKER_CERT_PATH=${TRAVIS_BUILD_DIR}
        - export DOCKER_HOST=tcp://${SERVER_HOST}:${SERVER_PORT}
      script:
        - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
              git clone https://github.com/bombergame/service-config &&
                  mv ./service-config/docker-compose.yml ./docker-compose.yml &&
                  ./service-config/decrypt.sh ./service-config . &&
                  docker-compose pull && docker-compose up -d
          fi
