language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/multiplayer-service .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/multiplayer-service;
          fi

    - stage: deploy
      script:
       - echo ${SSH_PASSWORD} | ssh ${SSH_USERNAME}@bombich.ru
       - git clone https://github.com/bombergame/multiplayer-service
       - git clone https://github.com/bombergame/service-config
       - echo ${SSH_PASSWORD} | sudo docker build -t bombergame/multiplayer-service .
       - sudo docker-compose -f ./service-config/docker-compose.yml up -d
       - exit
