language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/multiplayer-service .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/multiplayer-service;
          fi

    - stage: deploy
      services:
        - docker
      before_script:
        - git clone https://github.com/bombergame/service-config
        - ./service-config/decrypt.sh ./service-config .
        - ls -al
      script:
        - docker-compose --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H bombich.ru:2376 -f ./service-config/docker-compose.yml --env_file=.env up
