language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/multiplayer-service .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/multiplayer-service;
          fi

    - stage: deploy
      services:
        - docker
      env:
        - DOCKER_TLS_VERIFY=1 COMPOSE_TLS_VERSION=TLSv1_2
      before_script:
        - export DOCKER_CERT_PATH=${TRAVIS_BUILD_DIR}
        - export DOCKER_HOST=tcp://${SERVER_HOST}:${SERVER_PORT}
        - git clone https://github.com/bombergame/service-config &&
              mv ./service-config/docker-compose.yml ./docker-compose.yml &&
              ./service-config/decrypt.sh ./service-config .
      script:
        - docker-compose pull && docker-compose up -d
