language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/multiplayer-service .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/multiplayer-service;
          fi

    - stage: deploy
      services:
        - docker
      env:
        - DOCKER_COMPOSE_VERSION=1.19.0 COMPOSE_TLS_VERSION=TLSv1_2 DOCKER_HOST=tcp://bombich.ru:2376
      before_script:
        - curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o ./docker-compose
        - chmod +x /usr/local/bin/docker-compose
        - git clone https://github.com/bombergame/service-config &&
              mv ./service-config/docker-compose.yml ./docker-compose.yml &&
              ./service-config/decrypt.sh ./service-config .
      script:
        - docker-compose --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem up -d
