// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package components

import (
	json "encoding/json"
	physics "github.com/bombergame/multiplayer-service/game/physics"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7b1c777DecodeGithubComBombergameMultiplayerServiceGameComponents(in *jlexer.Lexer, out *MovementMessageData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "step_size":
			out.StepSize = physics.Integer(in.Int32())
		case "min_step_interval":
			out.MinStepInterval = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b1c777EncodeGithubComBombergameMultiplayerServiceGameComponents(out *jwriter.Writer, in MovementMessageData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"step_size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.StepSize))
	}
	{
		const prefix string = ",\"min_step_interval\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.MinStepInterval))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MovementMessageData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b1c777EncodeGithubComBombergameMultiplayerServiceGameComponents(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MovementMessageData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b1c777EncodeGithubComBombergameMultiplayerServiceGameComponents(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MovementMessageData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b1c777DecodeGithubComBombergameMultiplayerServiceGameComponents(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MovementMessageData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b1c777DecodeGithubComBombergameMultiplayerServiceGameComponents(l, v)
}
