// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package components

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3a4fd032DecodeGithubComBombergameMultiplayerServiceGameComponents(in *jlexer.Lexer, out *Transform) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "position":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Position).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3a4fd032EncodeGithubComBombergameMultiplayerServiceGameComponents(out *jwriter.Writer, in Transform) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"position\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Position).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transform) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3a4fd032EncodeGithubComBombergameMultiplayerServiceGameComponents(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transform) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3a4fd032EncodeGithubComBombergameMultiplayerServiceGameComponents(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transform) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3a4fd032DecodeGithubComBombergameMultiplayerServiceGameComponents(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transform) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3a4fd032DecodeGithubComBombergameMultiplayerServiceGameComponents(l, v)
}
