// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package objects

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE5471c0bDecodeGithubComBombergameMultiplayerServiceGameObjects(in *jlexer.Lexer, out *MessageData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "object_id":
			out.ObjectID = ObjectID(in.Int64())
		case "object_type":
			out.ObjectType = ObjectType(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5471c0bEncodeGithubComBombergameMultiplayerServiceGameObjects(out *jwriter.Writer, in MessageData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"object_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ObjectID))
	}
	{
		const prefix string = ",\"object_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ObjectType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE5471c0bEncodeGithubComBombergameMultiplayerServiceGameObjects(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5471c0bEncodeGithubComBombergameMultiplayerServiceGameObjects(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE5471c0bDecodeGithubComBombergameMultiplayerServiceGameObjects(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5471c0bDecodeGithubComBombergameMultiplayerServiceGameObjects(l, v)
}
