// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package gamestate

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (State) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*State) UnmarshalJSON([]byte) error        { return nil }
func (State) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*State) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GameState *State
