// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package solidwalls

import (
	json "encoding/json"
	objects "github.com/bombergame/multiplayer-service/game/objects"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC77e5303DecodeGithubComBombergameMultiplayerServiceGameObjectsWallsSolid(in *jlexer.Lexer, out *MessageData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "object_id":
			out.ObjectID = objects.ID(in.Int64())
		case "transform":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Transform).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC77e5303EncodeGithubComBombergameMultiplayerServiceGameObjectsWallsSolid(out *jwriter.Writer, in MessageData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"object_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ObjectID))
	}
	{
		const prefix string = ",\"transform\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Transform).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC77e5303EncodeGithubComBombergameMultiplayerServiceGameObjectsWallsSolid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC77e5303EncodeGithubComBombergameMultiplayerServiceGameObjectsWallsSolid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC77e5303DecodeGithubComBombergameMultiplayerServiceGameObjectsWallsSolid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC77e5303DecodeGithubComBombergameMultiplayerServiceGameObjectsWallsSolid(l, v)
}
