// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package rooms

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (GameState) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GameState) UnmarshalJSON([]byte) error        { return nil }
func (GameState) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GameState) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GameState *GameState
